---
# Prereq

- name: create base installation directory
  file: path={{ java_base_install_dir }} mode=0755 state=directory

# Install

# Online install - Currently Unavailable
#- name: online install | download java
#  get_url: url=http://tbc/{{ java_version }}.tar.gz dest=/var/tmp/{{ java_version }}.tar.gz
#- name: online install | extract java installation
#  unarchive: src=/var/tmp/{{ java_version }}.tar.gz copy=no dest={{ java_base_install_dir }}/ mode=0700 creates={{ java_base_install_dir }}/{{ java_version }}/bin/java
#  when: java_online_install

# Offline Install
- name: offline install | copy and extract java installation
  unarchive: src={{ java_installer_path }} dest={{ java_base_install_dir}}/ mode=0700 creates={{ java_base_install_dir}}/{{ java_version }}/bin/java
  when: not java_online_install

# Prepare runtime
- name: grant directory permissions to java user for installation directory
  file: path={{ java_base_install_dir}}/{{ java_version }} owner=root group=root mode=0755 recurse=true
- name: create symlink to java installation
  file: src={{ java_base_install_dir}}/{{ java_version }} path={{ java_base_install_dir}}/java state=link force=yes
